Hw 1
o-naichenko/nodejs-hw-01 pull request #1
Opened 2021-04-13 22:34 UTC by o-naichenko

2021-04-15 21:14 UTC, SergeiKBB requested changes

2021-04-15 21:14 UTC, SergeiKBB commented on contacts.js
> +    console.table(contacts)
Почему бы не сделать ретерн контактов с этой функции и ты смог бы использовать её дальше в коде для получения списка контактов? А выводил бы в таблицу непосредствено в файле index.js

2021-04-15 21:14 UTC, SergeiKBB commented on contacts.js
> +    console.table(contacts.filter(({ id }) => id === contactId))
Было бы хорошо добавить провекру, что фильтер вернул какой-то контакт, в противном случае вывести сообщение что контакта с таким айди нету

2021-04-15 21:14 UTC, SergeiKBB commented on contacts.js
> +    await fs.writeFile(contactsPath, JSON.stringify(remainingContacts))
Смотри, тут было бы хорошо оптимизировать код. Что будет если в твоей базе нету контакта с таким айди? Тебе всеравно прийдется перезаписать файл. Это забирает время и память. Это не есть хорошо. Если ты воспользуешся своей функциею  `getContactById` и проверишь результат который она возвращает (перед этим конечно же нужно её переписать, что ты она возвращала значение) если она ничего не вернула тогда тебе и не нужно перезаписывать файл а просто можешь вывести сообщение что такого контакта нету

2021-04-16 12:52 UTC, o-naichenko commented on contacts.js
> +    console.table(contacts)
так, одразу була така ідея, та чомусь вирішив що функція одразу має виводити в консоль

2021-04-17 12:58 UTC, o-naichenko commented on contacts.js
> +    await fs.writeFile(contactsPath, JSON.stringify(remainingContacts))
Згоден, логічно. і дякую, зрозумів що у мене біда з async

2021-04-17 13:00 UTC, o-naichenko commented on contacts.js
> +    console.table(contacts.filter(({ id }) => id === contactId))
Тут також поверне помилку console.error(`No contact with ID: ${contactId} found`) при виконанні removeContact(contactId)

2021-04-17 18:52 UTC, SergeiKBB commented on index.js
> +      contacts = await contactsAPI.listContacts()
Почему переменая объявленая без оператора?

2021-04-17 18:52 UTC, SergeiKBB commented on contacts.js
> +async function listContacts() {
Функции лучше всего называть каким-то действием. Например - getListOfContacts

2021-04-17 18:53 UTC, SergeiKBB reviewed
Ещё пару минорных коментов. Пофиксишь и можно мерджить

2021-04-18 20:49 UTC, o-naichenko commented on index.js
> +      contacts = await contactsAPI.listContacts()
тому що я знатно тупанув! ..здивований, що воно працює і так о_О, чому?

2021-04-18 20:54 UTC, o-naichenko commented on contacts.js
> +async function listContacts() {
подумав що list як дієслово теж підходить, та згоден, що getListOfContacts значно описовіше. p.s. прогуглив що list в перекладі - "заносити в список", тож не listContact взагалі не підходить для назви цієї функції, тож дякую!

2021-04-19 16:53 UTC, SergeiKBB approved these changes
Хороша робота!

2021-04-19 16:54 UTC, merged